services:
  api-bridge:
    image: willxd123/api-bridge-sw2:latest # <-- Imagen ya construida
    container_name: api-bridge-sw2
    restart: unless-stopped
    ports:
      - "3003:3003"
    extra_hosts:
      # Permite al bridge llegar a la clínica (puerto 3000) en el host
      - "host.docker.internal:host-gateway"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-fisioterapia
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Para que reciba webhooks públicos y genere bien las URLs:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://18.223.0.133:5678 # <-- Tu IP de AWS colocada automáticamente
      - GENERIC_TIMEZONE=America/La_Paz
      - TZ=America/La_Paz
      # Comunicación con el Bridge (usa el nombre del contenedor en la misma red)
      - BRIDGE_URL=http://api-bridge-sw2:3003
      - BRIDGE_API_KEY=${BRIDGE_API_KEY}
      # Comunicación con Clínica (usa host.docker.internal porque está en otro docker-compose)
      - CLINICA_N8N_URL=http://host.docker.internal:3000
      - N8N_API_KEY=${N8N_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      # Permite a n8n llegar a clinica corriendo en el host
      - "host.docker.internal:host-gateway"
    depends_on:
      - api-bridge

volumes:
  n8n_data:
    name: n8n-fisioterapia-data
